AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - Count
Resources:
  BucketToCopy:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: TestKey
          Value: my bucket %d
        - Key: Another key
          Value: "%d value"
    Count: 3
